import type { Metadata } from "next";
import local from "next/font/local";
import "./globals.css";

const font = local({ src: "./fonts/Exo2-VariableFont_wght.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} custom-scrollbar`}>{children}</body>
    </html>
  );
}
