import type { Metadata } from "next";
import local from "next/font/local";
import "./globals.css";
import Toast from "./_frags/toast";

const font = local({ src: "./fonts/Exo2-VariableFont_wght.ttf" });

export const metadata: Metadata = {
  title: "AirSage | Daily Aqi & Weather",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} custom-scrollbar bg-black text-zinc-50`}
      >
        <Toast>{children}</Toast>
      </body>
    </html>
  );
}
